### ISSUE TITLE
Feedback Sprint 1 Datadashboard

### ISSUE THREAD

**Issue by nerdale** [monicelica/cdmx-2018-06-bc-core-am-data-dashboard#6]
Hola @monicelica y @AMHymyilee 
He estado revisando el proyecto y tengo algunos comentarios:

1. Que pasó con el tema de UX? no lo encontré en el repositorio, no hay información sobre la investigación y descubrimiento de usuarios, sintesis, sketching de baja y alta fidelidad.

2. Felicitaciones por tener la visión de TDD, lo puedo notar en el archivo **data.js** por la estructura de las funciones tal como lo pide el test :clap:

3. Recuerden utilizar HTML semántico `<header></header> <section></section> <aside></aside> <footer></footer> <article></article>`

4. Ya veo un trabajo lógico pero les recomiendo comenzar a trabajar con la data a profundidad lo antes posible (se encontrarán con toda la lógica para jalar la información y hacer los cálculos) y plasmar tanto visual como funcionalmente lo que tienen pensado para el proyecto.

Espero puedan avanzar lo que más puedan para poder cumplir con el deadline del sprint 2 :muscle:

**Comment by monicelica** [comment]
Gracias por el feedback :), si ya estamos trabajando en el desarrollo del UX para así poder ponernos al corriente, y efectivamente estamos en el proceso de manejar y entender la data, también tomaremos mucho en cuenta la semántica del html, gracias :)

**Comment by nerdale** [comment]
Perfecto, daré por cerrado el issue :smile: 
:rocket:
